services:
  # 1. EVOLUTION API
  evolution_api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:latest
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      # Mapea el puerto 44222 (externo) al 8080 (interno)
      # Esto permite que Nginx le hable en el 44222
      - "${EVOLUTION_API_PORT:-44222}:8080"
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
    env_file:
      - .env
    expose:
      - 8080
    environment:
      # Timeouts vitales para evitar desconexiones
      - WEBSOCKET_TIMEOUT=120000
      - CONNECTION_TIMEOUT=30000
      - QRCODE_LIMIT=30
      - DEL_INSTANCE_ON_DISCONNECT=false
      # Disfraz para WhatsApp
      - CONFIG_SESSION_PHONE_CLIENT="Evolution API"
      - CONFIG_SESSION_PHONE_NAME=Chrome
      - CONFIG_SESSION_OS=Ubuntu
      # Redis
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis:6379/0
      - CACHE_LOCAL_ENABLED=false

  # 2. REDIS
  redis:
    image: redis:latest
    restart: always
    networks:
      - evolution-net
    container_name: redis
    command: redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"

  # 3. POSTGRES
  postgres:
    container_name: postgres
    image: postgres:15
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000", "-c", "listen_addresses=*"]
    restart: always
    ports:
      # CAMBIO REALIZADO: Usamos 5445 externo.
      # 5432 y 5433 estaban ocupados.
      - "5445:5432"
    environment:
      - POSTGRES_USER=${POSTGRESS_USER:-evolution}
      - POSTGRES_PASSWORD=${POSTGRESS_PASS:-evolution}
      - POSTGRES_DB=evolution
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432

  # 4. TU CEREBRO (Python)
  mi-cerebro-py:
    build: ./cerebro
    container_name: cerebro_python
    restart: always
    ports:
      - "8000:8000"
    networks:
      - evolution-net
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
      - GOOGLE_API_KEY=AIzaSyAI1jz6RJFyUTzMXfvHlnFBrafSLJ7s3ls
      # IMPORTANTE: Aqu√≠ la URL interna es correcta (http://evolution_api:8080)
      # porque se hablan de contenedor a contenedor
      - EVOLUTION_URL=http://evolution_api:8080
      - EVOLUTION_API_KEY=${AUTHENTICATION_API_KEY:-admin}
      - PORT=8000
    depends_on:
      - evolution_api

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge